// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVdH_fN2nNDzQQXtyWU4UT6HeH_MCW8sQ',
    appId: '1:157987402705:web:cbd54b399288fbcbf0e6f0',
    messagingSenderId: '157987402705',
    projectId: 'medismart-app-d5f03',
    authDomain: 'medismart-app-d5f03.firebaseapp.com',
    storageBucket: 'medismart-app-d5f03.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAzCpeuzSKpzc7hxkoQx-DVT88KP2VN2o',
    appId: '1:157987402705:android:e5715e591dd15ad1f0e6f0',
    messagingSenderId: '157987402705',
    projectId: 'medismart-app-d5f03',
    storageBucket: 'medismart-app-d5f03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC418tzoPI8w_wjMJfx0Q4UvzzC7pNPrmo',
    appId: '1:157987402705:ios:9b5dfbb4035fe2b9f0e6f0',
    messagingSenderId: '157987402705',
    projectId: 'medismart-app-d5f03',
    storageBucket: 'medismart-app-d5f03.firebasestorage.app',
    iosBundleId: 'com.example.medismartApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC418tzoPI8w_wjMJfx0Q4UvzzC7pNPrmo',
    appId: '1:157987402705:ios:9b5dfbb4035fe2b9f0e6f0',
    messagingSenderId: '157987402705',
    projectId: 'medismart-app-d5f03',
    storageBucket: 'medismart-app-d5f03.firebasestorage.app',
    iosBundleId: 'com.example.medismartApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVdH_fN2nNDzQQXtyWU4UT6HeH_MCW8sQ',
    appId: '1:157987402705:web:45cfbb7db6d10571f0e6f0',
    messagingSenderId: '157987402705',
    projectId: 'medismart-app-d5f03',
    authDomain: 'medismart-app-d5f03.firebaseapp.com',
    storageBucket: 'medismart-app-d5f03.firebasestorage.app',
  );
}
